events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 3000;

        location = /sell {
            return 301 /sell/;
        }

        location /sell/ {
            alias /home/app/Seller/frontend/dist/;
            try_files $uri $uri/ /sell/index.html;
        }

        location /admin {
            proxy_pass http://localhost:3003;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
        }

        location /api/v0/checkout/ {
            proxy_pass http://localhost:3014/api/v0/checkout/;
            proxy_set_header Host $host;
        }

        location /api/v0/ {
            proxy_pass http://localhost:3013/api/v0/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://localhost:3002;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
        }
    }
}
